### ISSUE TITLE
Fix the duplicate LastPeriodScreen function. 

### ISSUE THREAD

**Issue by sahilit** [sarthology/ovuli#100]
The LastPeriodScreen has repeated code.
Check and remove the duplicated code and fix the bug.

![Screenshot 2020-03-25 at 10 57 49 PM](https://user-images.githubusercontent.com/30876300/77566746-1a409a00-6eec-11ea-8d13-ec8e571e088a.png)

**Comment by Rits1272** [comment]
All the bugs have already been resolved in #101

**Comment by dibakar95** [comment]
Hi, I am a GSSoC 20 participant. Can I take this issue? @sahilit

**Comment by sahilit** [comment]
Yes, go on @dibakar95
