### ISSUE TITLE
Add validation logic so that Name field is not left blank

### ISSUE THREAD

**Issue by jamesgeorge007** [sarthology/ovuli#109]
Presently, the user can proceed by leaving the `Name` field empty which shouldn't be the case.

Add validation logic here:-
https://github.com/sarthology/ovuli/blob/09cd773d4fb14c62da81d57e400a830c040b1383/src/screens/ProfileScreen/YourNameScreen.js#L30

**Comment by iharshit009** [comment]
Hi @jamesgeorge007  I would like to work on this...
