### ISSUE TITLE
Implementing Eslint and Prettier 

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#11]
Adding Eslint and Prettier to Ovuli

**Comment by varunvme** [comment]
I would like to work on this task. I'll install basic configuration files and installing neccesary packages would add appropriate dev-tools to package.json

**Comment by sarthology** [comment]
Alright then, GO GO GO !!

**Comment by vipuldcoder** [comment]
I am interested to work with the issue.

**Comment by sahilit** [comment]
@guptavarun619 is already working on this issue. If he is unable to complete the issue we will assign it to you @vipuldcoder

**Comment by sarthology** [comment]
@vipuldcoder check the PR by @guptavarun619 there are some errors.
