### ISSUE TITLE
Language page is broken 

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#115]
Not merge properly. Please fix it. 

![image](https://user-images.githubusercontent.com/3650216/77816132-3ad44400-70e6-11ea-941e-8c6f0098b07e.png)

it should look like [this](https://github.com/sarthology/ovuli/blob/master/wireframes/onboard-wirefames/onboard-page1.png)

**Comment by Samriddhi25** [comment]
can I fix this

**Comment by sarthology** [comment]
Sure
