### ISSUE TITLE
Create setting page

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#118]
Use wireframes to make  settings page.

![image](https://user-images.githubusercontent.com/3650216/77816270-76bbd900-70e7-11ea-82aa-cf90681309ef.png)

**Comment by Samriddhi25** [comment]
Can I take this

**Comment by sarthology** [comment]
Nope 😅 one at a time.

**Comment by Samriddhi25** [comment]
Now can I take this 😁

**Comment by sarthology** [comment]
Sure
