### ISSUE TITLE
Linking Second Last period and Third Last period pages

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#119]
<img width="1005" alt="Screenshot 2020-03-28 at 11 32 12 AM" src="https://user-images.githubusercontent.com/3650216/77816300-c7333680-70e7-11ea-8f13-4b9921c7bf30.png">

In case the person choose no to "Do you know your cycle page?"
After the last period screen, Second last period screen will come and the third last period will come.

The calculation will done using `calculateAverageCycle` function from ovuli.js

**Comment by Rits1272** [comment]
May I work on this issue @sarthology?
