### ISSUE TITLE
Adding pre-commit checks using husky 

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#12]
Use husky to add pre commit hooks and enforce Eslint setting.

**Comment by vngarg** [comment]
Now I can work on this ??

**Comment by iamsomraj** [comment]
I would love to work on this

**Comment by heisastark** [comment]
Hi sir, I'd really like to work on this issue

**Comment by sarthology** [comment]
@iamsomraj You go ahead with this.

**Comment by sarthology** [comment]
@heisastark I have something for you in mind hold on.

**Comment by heisastark** [comment]
@sarthology Sure sir

**Comment by vipuldcoder** [comment]
I want to work with the issue.
