### ISSUE TITLE
Add contributing MD to Docusaurus 

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#121]
https://docusaurus.io/docs/en/site-creation
https://docusaurus.io/docs/en/tutorial-create-pages

Read the documentation carefully and add the [CONTRIBUTING.md](https://github.com/sarthology/ovuli/blob/master/CONTRIBUTING.md) in it.

**_REMEMBER THE BRANCH IS NOT MASTER IT'S Docusaurus_**

**Comment by shreyakapoor08** [comment]
can I work on this ? @sarthology
