### ISSUE TITLE
Changing the style of Docusaurus 

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#122]
https://docusaurus.io/docs/en/api-pages
https://docusaurus.io/docs/en/site-config

use our theme colors for Docusaurus. Currently it looks like this.
<img width="1552" alt="Screenshot 2020-03-28 at 11 47 28 AM" src="https://user-images.githubusercontent.com/3650216/77816610-e7fc8b80-70e9-11ea-9be4-75bfdb9f5a5b.png">

**Comment by Samriddhi25** [comment]
What are we required to do here

**Comment by aditianshu** [comment]
Can I be assigned this issue? I have experience working in React

**Comment by sarthology** [comment]
@aditianshu I think it's already done.
