### ISSUE TITLE
Remove the Unwanted files and links

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#123]
<img width="1187" alt="Screenshot 2020-03-28 at 11 50 28 AM" src="https://user-images.githubusercontent.com/3650216/77816652-53def400-70ea-11ea-9b4f-44a2f1e839eb.png">
<img width="992" alt="Screenshot 2020-03-28 at 11 49 56 AM" src="https://user-images.githubusercontent.com/3650216/77816644-41fd5100-70ea-11ea-88c7-cca1eaa59cf9.png">

Replace dummy links with relevant links 
like 
- contributing.md
- designsystem.md

**Comment by shreyakapoor08** [comment]
can I work on this @sarthology

**Comment by sarthology** [comment]
yes

**Comment by shreyakapoor08** [comment]
@sarthology PR raised :) If any changes are required, Kindly let me know :)
