### ISSUE TITLE
Font PT-SANS problem is still there.

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#124]
I recommend adding the PT-San in assets folder it's a free font.

![image](https://user-images.githubusercontent.com/3650216/77816709-de275800-70ea-11ea-97f0-f8001c89cd39.png)

**Comment by sahilit** [comment]
@iharshit009 can you look into it.
I think you forgot to implement in some screen

**Comment by iharshit009** [comment]
@sahilit I have just now checked but it worked correctly in my local...

**Comment by sahilit** [comment]
Fixed

**Comment by sahilit** [comment]
Fixed
