### ISSUE TITLE
Make left days module in home page.

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#136]
**_Few pointers:_**
- The circle should Increase as the Period date comes near
- Use the library logic to find days left 
- It's days, not date 

<img width="413" alt="Screenshot 2020-04-01 at 8 30 42 PM" src="https://user-images.githubusercontent.com/3650216/78152952-27173d80-7458-11ea-8d5a-9ae97144de92.png">

**Comment by aysp-99** [comment]
Hi! I'd like to work on this issue.

**Comment by iharshit009** [comment]
HI @sarthology can I work on this issue?

**Comment by Rits1272** [comment]
May I work on this @sarthology?

**Comment by sahilit** [comment]
@aysp-99 are you working on it?

**Comment by aysp-99** [comment]
Yes Sahil sir. I am working on it.

**Comment by sahilit** [comment]
@aysp-99  If you have any issues you can ask for help.

**Comment by Rits1272** [comment]
May I work on this @sarthology
