### ISSUE TITLE
Make how do you feel feature for Home Page.

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#137]
**_Few Pointers:_**
- It will a left-right slider 
- Emojis can be "🤩,🙁,☹️,😢,😭,🤕,😁,☺️,🥰,😒,😩"
- Each associated with a feeling 
- Each entry will save in Local DB with the time stamp.

<img width="387" alt="Screenshot 2020-04-01 at 8 40 02 PM" src="https://user-images.githubusercontent.com/3650216/78153688-f84d9700-7458-11ea-95e1-dd57f4c4095e.png">

**Comment by Rits1272** [comment]
May I work on this issue @sarthology ?

**Comment by dibakar95** [comment]
Can I work on this issue too.
