### ISSUE TITLE
Make custom calendar component for home page

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#138]
**_Few pointers:_**
- This should show history also 
- Red is a period dates 
- Blue is ovulation 

<img width="438" alt="image" src="https://user-images.githubusercontent.com/3650216/78155282-e240d600-745a-11ea-9f61-fe72044d8bfd.png">

**Comment by Samriddhi25** [comment]
Can I take this issue

**Comment by Samriddhi25** [comment]
Can I take this issue

**Comment by dibakar95** [comment]
I can work upon this issue.

**Comment by dibakar95** [comment]
@sarthology what data structure should I use to implement the history of the user to render it in the Calendar. Please guide.
