### ISSUE TITLE
Make the language conversion functionality

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#139]
It's time that we make this functionality live and use the language base files for the same.

**Please do this in guidance of mentors**

**Comment by sarthology** [comment]
Mentor to reach out: @narender2031

**Comment by iharshit009** [comment]
Hi @sarthology I would like to work on this functionality

**Comment by narender2031** [comment]
Hey @iharshit009, Please start with configuring `i18n`

Create a PR with `i18n` configuration

**Comment by iharshit009** [comment]
> Hey @iharshit009, Please start with configuring `i18n`
> 
> Create a PR with `i18n` configuration
Okay

**Comment by dibakar95** [comment]
@sarthology can I work upon this issue.

**Comment by narender2031** [comment]
hey @dibakar95, @iharshit009  is already doing this.

**Comment by narender2031** [comment]
@iharshit009 any updates?

**Comment by iharshit009** [comment]
> @iharshit009 any updates?

Need 1 day more,  would make a PR by tomorrow morning.

**Comment by narender2031** [comment]
@iharshit009 if you need any help please ping me.

**Comment by Rits1272** [comment]
@iharshit009 are you still working on this?

**Comment by iharshit009** [comment]
I am still working on it @Ritik Jain <ritikjain1272@gmail.com>
