### ISSUE TITLE
Replace the PNG icons with SVG icons

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#143]
![image](https://user-images.githubusercontent.com/3650216/78163080-7a43bd00-7465-11ea-98bf-edbf13bdac45.jpeg)

**Comment by ranjal007** [comment]
@sarthology  I need to work on this issue for GSSOC20 .Please assign it to me.

**Comment by dibakar95** [comment]
Can you assign me this task. #GGSOC20 @sarthology

**Comment by ranjal007** [comment]
@sarthology sir, I need to change the png icons in the wireframe or in the code?

**Comment by sarthology** [comment]
Code. You will find the files [here](https://github.com/sarthology/ovuli/tree/master/wireframes/assets)

**Comment by sahilit** [comment]
@ranjal007 are you working on it?

**Comment by shreyakapoor08** [comment]
can i work on it?

**Comment by sahilit** [comment]
Yes go on.
