### ISSUE TITLE
Remove unwanted categories and add everything under on section for now  

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#144]
<img width="211" alt="Screenshot 2020-04-01 at 10 27 03 PM" src="https://user-images.githubusercontent.com/3650216/78164786-ede6c980-7467-11ea-9ec7-321d8118132a.png">

**Comment by shreyakapoor08** [comment]
Kindly assign me this

**Comment by sarthology** [comment]
Also, remove these link and add a GitHub link to the repo

<img width="279" alt="image" src="https://user-images.githubusercontent.com/3650216/78165098-6fd6f280-7468-11ea-9cb5-a90429d2c1dd.png">

**Comment by sarthology** [comment]
Also this 

<img width="1439" alt="Screenshot 2020-04-01 at 10 32 32 PM" src="https://user-images.githubusercontent.com/3650216/78165263-b0cf0700-7468-11ea-96ce-b4d1cc99aa09.png">
