### ISSUE TITLE
Update lint-staged config to avoid the warning

### ISSUE THREAD

**Issue by jamesgeorge007** [sarthology/ovuli#145]
As of `lint-staged-v10`, modifications done are automatically added to the git commit index. Still having `git add` as part of the config triggers the following warning:-

```sh
⚠ Some of your tasks use `git add` command. Please remove it from the config since all modifications made by tasks will be automatically added to the git commit index.
```

https://github.com/sarthology/ovuli/blob/7db2c94ffbaca3675c475920656e32f6f8602074/package.json#L18

https://github.com/sarthology/ovuli/blob/7db2c94ffbaca3675c475920656e32f6f8602074/package.json#L22

**Comment by NANDINI-star** [comment]
i would like to work on this issue @jamesgeorge007

**Comment by pa7ri** [comment]
I would like to work on it :)

**Comment by jamesgeorge007** [comment]
@pa7ri please go ahead 👍
