### ISSUE TITLE
update the README.md with contribution conventions. 

### ISSUE THREAD

**Issue by narender2031** [sarthology/ovuli#149]
1. Start using functional components. 

2. Stat using module resolver. 
e.g 
**bad practice**
```
import LanguageScreen from '../../languageScreen';
```
**Good Practice**

```
import LanguageScreen from '@/screens/profileScreen/LanguageScreen'
```

**reason**: 
- Easy to debug the file.
- increase readability.

3. Don't use Inline styles
4. Please take create of the variable names. A variable name should define the function work. 
5. If you are using colors. Then please create a color object for your component. 
  - Please add the outside the component scope like styles object. Define this after the Imports. 

e.g. 
```
const colors = {
   colorName: 'colorCode'
}
```

reason: 
In the future, if we have to change the color so we don't need to find them. This makes easy to find and updates.

**Comment by sahilit** [comment]
It can be added in contribution.md

**Comment by shreyakapoor08** [comment]
@narender2031 can I work on it?

**Comment by saloniankita** [comment]
Kindly assign this issue to me @narender2031
