### ISSUE TITLE
Creating "Calculate your cycle period" page

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#16]
In this page you will be redirected if you don't know your average cycle period. In this there will be a Calendar like #8. Use [this](https://github.com/mcnamee/react-native-starter-kit) package only.

**Comment by robot-with-feelings** [comment]
i'd like to work on this!

**Comment by sarthology** [comment]
Alright then, All yours. Go Go Go !!

**Comment by sahilit** [comment]
Hey, @robot-with-feelings what is the status, are you still working on it?

**Comment by robot-with-feelings** [comment]
I'm working on another issue, you may reassign this to someone else if that's okay!

**Comment by Samriddhi25** [comment]
I can work on this

**Comment by sahilit** [comment]
@Samriddhi25 you can start working on this issue.
@sarthology can you assign this to @Samriddhi25.

**Comment by sarthology** [comment]
@Samriddhi25  Go on

**Comment by sarthology** [comment]
@Samriddhi25 No update yet

**Comment by Rits1272** [comment]
Are  you still working on it @Samriddhi25 ?? Can I work on this issue @sarthology

**Comment by sarthology** [comment]
Go on !!

**Comment by Samriddhi25** [comment]
@sarthology  sorry for the delay, I have created the PR for the issue please review it.
