### ISSUE TITLE
Adding navigation to on boarding pages

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#25]
Use should be able to navigate through the next button. The sequence is following:

1. YourNameScreen
2. AvgCycleScreen
3. LastPeriodScreen

![image](https://user-images.githubusercontent.com/3650216/75662086-87b62d80-5c94-11ea-9025-e27b331cc7fc.png)

**Comment by vngarg** [comment]
I can work on this too ..

**Comment by heisastark** [comment]
Can i work on this?

**Comment by sarthology** [comment]
@heisastark Yes, was waiting for you only. Let's kill it.

**Comment by vngarg** [comment]
I can work on this ...
But Where this file needs to be created ??

**Comment by sarthology** [comment]
In the profilescreen

**Comment by ranjal007** [comment]
I need to work on this issue. Please assign it to me.

**Comment by vngarg** [comment]
I can work on this ...assign this to me

**Comment by falguniraina** [comment]
can i work on this!!

**Comment by sarthology** [comment]
@falguniraina Yes

**Comment by Rits1272** [comment]
Hey @sarthology can I solve this issue???

**Comment by Samriddhi25** [comment]
Can I take this issue?

**Comment by sarthology** [comment]
I just assigned one to you.

**Comment by Samriddhi25** [comment]
Yes ok

**Comment by Rits1272** [comment]
Hey @sarthology! May I take this up??

**Comment by Major2001** [comment]
@sarthology  If this issue is free, I would like to work on it

**Comment by sarthology** [comment]
Harshit solved it. If you want to add anything. Feel free to add.
