### ISSUE TITLE
Write test case for ovuli.js Library

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#27]
Use [Jest](https://jestjs.io/docs/en/tutorial-react-native) to write test cases for ovuli.js location `src/utils/ovuli.js`.

**Comment by iharshit009** [comment]
Hi @sarthology , I would like to work on this issue...

**Comment by iharshit009** [comment]
@sarthology  Please guide me for this issue, I would like to work on it...

**Comment by sarthology** [comment]
DM me.

**Comment by Rits1272** [comment]
Are you still working on it @iharshit009? May I work on this issue @sarthology?

**Comment by iharshit009** [comment]
Hey @rits1272 I am working on this...
Kindly take any other issue
