### ISSUE TITLE
Creating splash screen in the app

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#29]
Creating splash screen for the ovuli app

**Comment by Rits1272** [comment]
Hey @sarthology can I work on this?

**Comment by sarthology** [comment]
Once you are done with #24

**Comment by iamsomraj** [comment]
I want to work on this.

**Comment by Major2001** [comment]
Can I work on this issue?

**Comment by sarthology** [comment]
Go on @Major2001

**Comment by Anjalidubey01** [comment]
Hey can i work on this issue??

**Comment by sarthology** [comment]
Let's see who submit's first.

**Comment by sarthology** [comment]
@Rits1272 im sending it to you
