### ISSUE TITLE
Add "Select language" page 

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#30]
Add Select Language page with option to select language like this.

![](https://github.com/kalontech/ReactNativeWheelPicker/raw/master/src/assets/pickerIos.gif)

 **_Libraries to look for:_**

https://github.com/kalontech/ReactNativeWheelPicker
https://github.com/rdhox/react-native-smooth-picker

**Comment by vipuldcoder** [comment]
I am interested to work with the issue.

**Comment by sarthology** [comment]
I am assigning this to you.

**Comment by vipuldcoder** [comment]
Let's get started :)

**Comment by adityasanil** [comment]
Can I work on this?

**Comment by sahilit** [comment]
@vipuldcoder are you still working on this issue?

**Comment by sarthology** [comment]
@adityasanil It's assigned to you now.

**Comment by adityasanil** [comment]
> @adityasanil It's assigned to you now.

Any deadline here?

**Comment by sarthology** [comment]
Well it was 48hrs

**Comment by adityasanil** [comment]
Well, I will push the code by tomorrow evening. That cool?

**Comment by Rits1272** [comment]
Can I work on this @sarthology ?
