### ISSUE TITLE
Removing dummy content from Docusaurus

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#31]
There are a lot of dummy content in the Docusaurus. Please remove it.

`branch: gh-pages`

**Comment by vngarg** [comment]
Could you please elaborate more ....
Which dummy content ?

**Comment by sarthology** [comment]
this

<img width="1090" alt="Screenshot 2020-03-03 at 4 22 07 PM" src="https://user-images.githubusercontent.com/3650216/75768846-2319d200-5d6b-11ea-9316-266b773cdd94.png">

**Comment by vngarg** [comment]
I can do this ...
Only this is or some more content is there which has to be removed ??

**Comment by FrozenGirl-spd** [comment]
Can you assign this to me please?

**Comment by harshita130602** [comment]
Could you please assign it to me.

**Comment by sarthology** [comment]
@FrozenGirl-spd You give it try. Make sure to complete it by today.

**Comment by msk4862** [comment]
@sarthology I want to work on this issue, If its not assigned to anyone else.

**Comment by msk4862** [comment]
@sarthology These dummy docs are being refered in docusaurus `siteConfig.js` and  `sidebars.json` files, Should I remove those references also?

**Comment by sarthology** [comment]
Yes and remove files as well.

**Comment by vipuldcoder** [comment]
Can I work on this issue?
