### ISSUE TITLE
Publishing  Docusaurus for GitHub Pages 

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#37]
Publish and push the code.

[Follow this Guide](https://docusaurus.io/docs/en/publishing#using-github-pages)

**Comment by AnushkaH** [comment]
Hi, kindly assign this to me.

**Comment by vngarg** [comment]
I had previously worked on this ....
I can work on this, assign this to me ..

**Comment by vngarg** [comment]
Which platform do I have to use ??
1. ZEIT
2.Github pages 
3. Netlify
4. render

**Comment by sarthology** [comment]
Follow the guide above

**Comment by vngarg** [comment]
@sarthology  This guide tells me different ways to deploy the site...
I'm asking that which platform should I use amongst thesd ??

**Comment by sahilit** [comment]
@vngarg you should follow Github pages

**Comment by vngarg** [comment]
![Screenshot from 2020-03-09 00-58-18](https://user-images.githubusercontent.com/49458871/76169741-44caed00-61a1-11ea-8dac-cba657599624.png)
@sarthology @sahilit While publishing it's showing me this error ...
Please help me with this ??

**Comment by vngarg** [comment]
@sahilit @sarthology Please help me with the above problem ...

**Comment by sarthology** [comment]
Have you made the build folder ?

**Comment by vngarg** [comment]
> Have you made the build folder ?

@sarthology Yes ..I have made the build folder inside /website folder..

**Comment by vngarg** [comment]
> Have you made the build folder ?

@sarthology Please help me with this problem ..

**Comment by sarthology** [comment]
Send the PR I will do after that.

**Comment by vngarg** [comment]
> Send the PR I will do after that.

@sarthology I had created the PR #58 ..
Please merge it ..
