### ISSUE TITLE
Adding on boarding pages to the app 

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#4]
Our app needs on boarding so the first task will be fairly simple make three screens
1. Add Name
2. Enter your average period cycle 
3. When was your last Period

The content of these tasks will be added in next few issues.

**Comment by iharshit009** [comment]
Hi @sarthology I Would like to work on this issue

**Comment by sarthology** [comment]
Go hit it. Change the container folder to screens and add there. Remember just add pages it's a basic tasks. Do it fast your team mates are waiting go go go

**Comment by ghost** [comment]
Hi @sarthology I would like to work on this. ⚡️

**Comment by sarthology** [comment]
@JoshuaPoddoku already assigned. How about this #6 ?

**Comment by sarthology** [comment]
Closed by #10

**Comment by ghost** [comment]
> @JoshuaPoddoku already assigned. How about this #6 ?

Yes that would be good @sarthology :smile:
