### ISSUE TITLE
add Badges in README.md

### ISSUE THREAD

**Issue by SohelRaja** [sarthology/ovuli#42]
I would like to add **git badges** like **forks, stars, watchers, pull request, issues, license, last commit, repo size, contributor** to the _README_ file. Please Assign me for this and this can be labelled as **gssoc20** and **easy** . @sarthology @sahilit @praveenscience @jamesgeorge007

**Comment by sarthology** [comment]
That's not a medium level task

**Comment by Basilleaf24** [comment]
@sarthology @sahilit @praveenscience @jamesgeorge007 
Pls assign me this issue, looking forward to contribute to it
