### ISSUE TITLE
Add new design to Splash-screen 

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#47]
Change the design of splash screen to this 

![image](https://user-images.githubusercontent.com/3650216/76296920-fae72180-62dc-11ea-8940-419c4fbb1562.png)

Get files in wireframes folder.

**Comment by Major2001** [comment]
I would like to work on this

**Comment by sarthology** [comment]
Can you do this in 48hrs ?

**Comment by Major2001** [comment]
I will try
