### ISSUE TITLE
Add new design to AvgCycleScreen 

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#49]
Change the current AvgCycleScreen page to this 

![image](https://user-images.githubusercontent.com/3650216/76297269-9a0c1900-62dd-11ea-845f-ff87ec1d88bd.png)

Check wireframe for files.

**Comment by Rits1272** [comment]
Can I work on this?

**Comment by sarthology** [comment]
Yes you can. Do check `wireframes/assets` folder for illustrations.
