### ISSUE TITLE
Create stack navigation for on boarding

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#5]
In this we have to add stacked [React Native Navigation](https://reactnavigation.org/docs/navigating) to pages added in #4.

**Comment by Rits1272** [comment]
I would like to work on this issue

**Comment by sarthology** [comment]
It has dependency on #4. Would like to first work on that ?

**Comment by Rits1272** [comment]
Yeah I would work on that first and then I will make stacknavigator @sarthology !

**Comment by Rits1272** [comment]
Can I work now @sarthology ?

**Comment by sarthology** [comment]
GO GO GO !!

**Comment by Major2001** [comment]
Can I also work for this issue?

**Comment by sahilit** [comment]
@Rits1272 is already working on this issue. If he is unable to complete the issue in next 48h we will assign it to you @Major2001
