### ISSUE TITLE
Save the Name, Average Cycle Period and Last Period using Async Storage.

### ISSUE THREAD

**Issue by sahilit** [sarthology/ovuli#56]
Currently, we are not Saving the Name, Average Cycle Period and Last Period entered by the user.
We want to save the data offline on the device of the user. 
Use async-storage and store the data on the user device.

Follow the guide below:
https://github.com/react-native-community/async-storage

**Comment by Rits1272** [comment]
May I work on this?

**Comment by sarthology** [comment]
Ohk

**Comment by kritikpancholi** [comment]
@Rits1272  are you still working on this?
