### ISSUE TITLE
Integrate ESLint with prettier

### ISSUE THREAD

**Issue by jamesgeorge007** [sarthology/ovuli#57]
Presently we've separate scripts to execute `eslint` and `prettier` checks. Well, we could leverage `eslint-plugin-prettier` to unify them. Also, the `pre-commit` hook is configured to run just the `format` script.

Please follow [these instructions](https://prettier.io/docs/en/integrating-with-linters.html#eslint).

**Comment by jamesjose03** [comment]
@jamesgeorge007 @sarthology I would like to take up this issue.

**Comment by jamesgeorge007** [comment]
@jamesjose03 please go ahead 👍
