### ISSUE TITLE
Adding content to "Add Name" Page

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#6]
We have to make simple input tag and a next button in this page.

![image](https://user-images.githubusercontent.com/3650216/75613463-05265480-5b54-11ea-9be6-6e9a56d71fca.png)

**Comment by Major2001** [comment]
I would like to work on this issue

**Comment by sarthology** [comment]
It has as dependency on #4. Would you like to first do that ?

**Comment by vngarg** [comment]
I would love to work on this ..

**Comment by goyalmuskan** [comment]
I want to work on this issue. Please assign it to me. 
@sarthology

**Comment by sarthology** [comment]
Alright then Go Go Go !

**Comment by Major2001** [comment]
Is this issue still free

**Comment by sarthology** [comment]
No !! check https://github.com/sarthology/ovuli/projects

**Comment by vipuldcoder** [comment]
I want to work on this issue.
