### ISSUE TITLE
zsh: command not found: ovuli

### ISSUE THREAD

**Issue by shan5742** [sarthology/ovuli#6]
After running `npm i -g ovuli` and then entering `ovuli` in the terminal I get `zsh: command not found: ovuli`

I have an ovuli directory in`/usr/local/Cellar/node/12.12.0/lib/node_modules`

**Comment by courtsimas** [comment]
looks like you installed npm originally with homebrew, which has some issues occasionally. try some of these potential solutions: https://stackoverflow.com/questions/38483711/npm-command-not-found-error-but-node-is-installed

**Comment by pavanjadhaw** [comment]
@shan5742 seems like ovuli is installed but the installation directory is not added to your path
I think the stackoverflow post linked by @courtsimas should resolve your issue as I couldnt reproduce this error on my local machine

**Comment by shan5742** [comment]
Hey, sorry must have missed the response here, seems that the --without options is no longer available in brew
