### ISSUE TITLE
Adding content to "Average cycle page"

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#7]
In this page we want a horizontal number slider something like this 

![](https://github.com/rdhox/react-native-smooth-picker/raw/master/assets/demo.gif)

**Comment by Samriddhi25** [comment]
I would like to work on this

**Comment by sarthology** [comment]
Alright then, GO GO GO !!

**Comment by sahilit** [comment]
Hey, @Samriddhi25 what is the status, are you still working on it?

**Comment by Samriddhi25** [comment]
> Hey, @Samriddhi25 what is the status, are you still working on it?

yes
