### ISSUE TITLE
Change Design of add name page

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#72]
Change this 
![image](https://user-images.githubusercontent.com/3650216/77146701-aba9a980-6ab1-11ea-9c47-df9f18336e1b.png)
to this
![](https://github.com/sarthology/ovuli/blob/master/wireframes/onboard-wirefames/onboard-page2.png?raw=true)

See `wireframes/assets` folder and use SVG icons.

**Comment by Major2001** [comment]
I would like to work on this

**Comment by sarthology** [comment]
Sure
