### ISSUE TITLE
Change Design of Select Language page

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#73]
From this 
![image](https://user-images.githubusercontent.com/3650216/77146851-0b07b980-6ab2-11ea-939c-032b9ddbba2d.png)
to this
![](https://github.com/sarthology/ovuli/blob/master/wireframes/onboard-wirefames/onboard-page1.png?raw=true)

**Comment by Samriddhi25** [comment]
I would like to contribute to this issue

**Comment by sarthology** [comment]
Remember 48 hrs
