### ISSUE TITLE
Problem in Github's Greeting action 

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#75]
Instead of greeting it's Throwing error every time.
<img width="1088" alt="Screenshot 2020-03-20 at 1 59 08 PM" src="https://user-images.githubusercontent.com/3650216/77147336-fc6dd200-6ab2-11ea-8210-b827f1753836.png">

**Comment by bansaljas** [comment]
Can I work on this issue?
And if you could elaborate a bit more on  the issue, it would be really helpful. Thankyou!

**Comment by sarthology** [comment]
Yes please.
