### ISSUE TITLE
Adding content to "Last period Page"

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#8]
Here it will be a calendar. We will be using [this Calendar](https://github.com/wix/react-native-calendars) package. 

Possibly this 
![](https://github.com/wix-private/wix-react-native-calendar/blob/master/demo/calendar.gif?raw=true)

**Comment by iharshit009** [comment]
Hi @sarthology, I would like to work on this issue next...

**Comment by vipuldcoder** [comment]
I am interested to work with the issue.
