### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Aman-Codes** [sarthology/ovuli#83]
@sarthology  As a GSSOC participant I would like to add a CODE_OF_CONDUCT.md file in this project. Please assign me this issue.

**Additional context**
### Screenshots

![code of conduct1](https://user-images.githubusercontent.com/54680709/77505634-beddc000-6e89-11ea-9dd5-f1e13ef6c6c9.PNG)
![code of conduct2](https://user-images.githubusercontent.com/54680709/77505638-c0a78380-6e89-11ea-8aa4-efcb21133da7.PNG)

**Comment by sarthology** [comment]
Not required

**Comment by Aman-Codes** [comment]
Ok Sir
