### ISSUE TITLE
Use text instead on images in every page 

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#86]
Currently everyone is using pngs for the text in every page. Please use text instead. The font that we are using in already mention in [Design System](https://github.com/sarthology/ovuli/blob/master/designsystem.md).

It should look exactly the same.

**Comment by Rits1272** [comment]
Can I work on this @sarthology

**Comment by sarthology** [comment]
Submit it by tomorrow.

**Comment by Rits1272** [comment]
Yeah sure
