### ISSUE TITLE
Make files for multiple languages in language base folder 

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#88]
Use Sample.json to create files for multiple languages (only Indian)
<img width="493" alt="Screenshot 2020-03-25 at 5 34 37 PM" src="https://user-images.githubusercontent.com/3650216/77534566-e8650e80-6ebe-11ea-92c1-f277841eecec.png">

**Comment by Samriddhi25** [comment]
I would like to take this issue

**Comment by sarthology** [comment]
Submit it by tomorrow.

**Comment by narender2031** [comment]
Can we add i18n for the language?

**Comment by sarthology** [comment]
Yes but for that also. We will need these json files right ?
