### ISSUE TITLE
App should remember that I have done the onboarding

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#89]
As now we are saving the data. App should remember that whether I have completed the on boarding or not.

If I have it should take me to home page Directly.

**Comment by Bhanu-mbvg** [comment]
Hey, can I take up this issue.

**Comment by bhngupta** [comment]
Hey, I can take up this issue?

**Comment by sarthology** [comment]
Submit it by tomorrow.

**Comment by bhngupta** [comment]
Can you guide me on how I go about this?

**Comment by sarthology** [comment]
Guide how ?

**Comment by iharshit009** [comment]
Hi @sarthology Should I work on this?

**Comment by Rits1272** [comment]
May I work on this @sarthology? @iharshit009 has already been assigned another issue
