### ISSUE TITLE
Adding documentation using docusaurus

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#9]
Setting up docusaurus in a separate branch.

Follow [Installation](https://docusaurus.io/docs/en/installation) here.

Remember it will a separate branch entirely names "gh-pages" so work wisely.

**Comment by vngarg** [comment]
I would love to work on it ..

**Comment by sarthology** [comment]
Alright, Just make sure the new branch should only have Docusaurus Code. GO GO GO !!
