### ISSUE TITLE
Adding Do you know you average cycle page

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#93]
You have to make a new page between add your name screen and Average Cycle screen.

This is how it looks 
![](https://github.com/sarthology/ovuli/blob/master/wireframes/onboard-wirefames/onboard-page-don't-know1.png?raw=true)

#### If yes
Then take them to AverageCyle page 

#### If no
Then take them to when was your last cycle page

**Comment by iharshit009** [comment]
Should I do this @sarthology ?

**Comment by sarthology** [comment]
wait.

**Comment by Rits1272** [comment]
May I work on this @sarthology ??

**Comment by sarthology** [comment]
@Rits1272 you work on #89
