### ISSUE TITLE
Add page to capture past period dates.

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#94]
Add these two new pages in the app

![](https://github.com/sarthology/ovuli/blob/master/wireframes/onboard-wirefames/onboard-page-don't-know2.png?raw=true)

and
![](https://github.com/sarthology/ovuli/blob/master/wireframes/onboard-wirefames/onboard-page-don't-know3.png?raw=true)

**Comment by Rits1272** [comment]
May I work on this @sarthology ?
