### ISSUE TITLE
Fix the fontFamily "PT-Sans" Bug

### ISSUE THREAD

**Issue by sahilit** [sarthology/ovuli#98]
Error message after running `expo start`

![Screenshot 2020-03-25 at 10 43 14 PM](https://user-images.githubusercontent.com/30876300/77565389-29bee380-6eea-11ea-8c7c-2e524b2985bd.png)

**Comment by Rits1272** [comment]
All the bugs have already been resolved in #101

**Comment by iharshit009** [comment]
Hi @sahilit Should I work on this ?
