### ISSUE TITLE
Fix the 'Can't find variable' bug

### ISSUE THREAD

**Issue by sahilit** [sarthology/ovuli#99]
The `please_select_your_language` image variable is not defined.
The image is located in the wireframes folder.
Find the image and import it in the `src/screens/ProfileScreen/LanguageScreen.js` page.

Error screenshot:
![Screenshot 2020-03-25 at 10 50 53 PM](https://user-images.githubusercontent.com/30876300/77566081-2a0bae80-6eeb-11ea-95e0-175d9dcbebf3.png)

**Comment by anishagoswami167** [comment]
CAN I TAKE THIS ISSUE?

**Comment by Rits1272** [comment]
All the bugs have already been resolved in #101

**Comment by anishagoswami167** [comment]
OKAY

**Comment by sahilit** [comment]
@anishagoswami167 you can work on the issue.
It is not been resolved

**Comment by sahilit** [comment]
@anishagoswami167  are you working on it

**Comment by chrischongyj** [comment]
Would like to work on this if you need another person.
